name: DSAgame
options:
  bundleIdPrefix: moji.education
  deploymentTarget:
    iOS: 17.0
targets:
  DSAgame:
    type: application
    platform: iOS
    sources: 
      - path: DSAgame
    resources:
      - path: DSAgame/Resources
        type: folder